# Generated by Django 4.2.5 on 2023-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='portions_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
