# Generated by Django 4.2.5 on 2023-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_recipe_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_count',
            field=models.TextField(null=True),
        ),
    ]
