# Generated by Django 4.2.5 on 2023-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_recipe_ingredients_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='verify',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
